# Generated by Django 5.0.6 on 2024-06-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.TextField(default='null'),
        ),
    ]
