# Generated by Django 5.0.6 on 2024-07-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_company_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('SDE', 'Software Developer'), ('PDE', 'Python Developer'), ('Director', 'Director'), ('AI/ML', 'AI/ML Developer'), ('HR', 'HR'), ('EP', 'Entrepreneur'), ('CE', 'Civil Engineer'), ('Law', 'Lawyer'), ('TL', 'Team Leader'), ('ME', 'Mechanical Engineer'), ('ECE/EEE', 'Electronics or Electrical Engineer'), ('CA', 'Accountant'), ('BA', 'Business Analyst'), ('DA', 'Data Analyst'), ('CEO', 'Chief Executive Officer')], max_length=100),
        ),
    ]
